### ISSUE TITLE
Top X leaderboard display in slack

### ISSUE THREAD

**Issue by butteredxtoast** [nathanborgo/hey-whatever#11]
allow users to @mention heywhatever and type enter 'leaderboard' to get the leaderboard at a glance

easy temp solution would be to have heywhatever return the park.at link to our hosted leaderboard

**Comment by nathanborgo** [comment]
<img width="562" alt="screen shot 2017-11-12 at 9 42 33 pm" src="https://user-images.githubusercontent.com/802806/32708960-e52295be-c7f2-11e7-9b64-efa898a80a23.png">
